//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BedSpace
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BedSpace()
        {
            this.BedSpacePlacements = new HashSet<BedSpacePlacement>();
            this.GenerateInspections = new HashSet<GenerateInspection>();
        }
    
        public int BedSpaceID { get; set; }
        public int RoomID { get; set; }
        public string RoomGender { get; set; }
        public string BedName { get; set; }
        public string BedAddress { get; set; }
        public string BedDescription { get; set; }
        public bool IsEnable { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> InspectionActionID { get; set; }
        public bool Status { get; set; }
    
        public virtual BedSpace BedSpace1 { get; set; }
        public virtual BedSpace BedSpace2 { get; set; }
        public virtual BedSpaceStatusLookUp BedSpaceStatusLookUp { get; set; }
        public virtual Room Room { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BedSpacePlacement> BedSpacePlacements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GenerateInspection> GenerateInspections { get; set; }
    }
}
