//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BedSpacePlacementMigration
    {
        public int Id { get; set; }
        public int BedSpaceplacementId { get; set; }
        public int OldBedSpaceId { get; set; }
        public int NewBedSpaceId { get; set; }
        public string OldBedSpaceName { get; set; }
        public string Remarks { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
