//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BedSpacePlacement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BedSpacePlacement()
        {
            this.Feedbacks = new HashSet<Feedback>();
            this.PersonGuests = new HashSet<PersonGuest>();
            this.PreCheckInDocumentations = new HashSet<PreCheckInDocumentation>();
            this.StudentContracts = new HashSet<StudentContract>();
        }
    
        public int BedSpacePlacementID { get; set; }
        public int BookingID { get; set; }
        public int BedSpaceID { get; set; }
        public System.DateTime MoveIn { get; set; }
        public System.DateTime MoveOut { get; set; }
        public Nullable<System.DateTime> CheckIn { get; set; }
        public Nullable<System.DateTime> CheckOut { get; set; }
        public bool IsEnable { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public string AccessibilityRequest { get; set; }
        public Nullable<int> GuestCount { get; set; }
        public string Description { get; set; }
        public Nullable<int> CardID { get; set; }
        public string TID { get; set; }
    
        public virtual BedSpace BedSpace { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feedback> Feedbacks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonGuest> PersonGuests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreCheckInDocumentation> PreCheckInDocumentations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentContract> StudentContracts { get; set; }
    }
}
