//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int BookingID { get; set; }
        public int PersonID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public int PriceConfigID { get; set; }
        public System.DateTime CheckInDate { get; set; }
        public Nullable<bool> IsCancel { get; set; }
        public bool IsEnable { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public string BookingNumber { get; set; }
        public Nullable<System.DateTime> CheckOutDate { get; set; }
        public string Channel { get; set; }
        public string PaymentType { get; set; }
        public string AccessibilityRequest { get; set; }
        public string CardLastDigits { get; set; }
        public string TranRef { get; set; }
        public string Message { get; set; }
        public string HearFromCode { get; set; }
        public Nullable<bool> Status { get; set; }
        public string HearFrom { get; set; }
        public string HearFromOther { get; set; }
        public string ImageUrl { get; set; }
        public string Source { get; set; }
        public string UniReferenceNo { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual Person Person { get; set; }
        public virtual PriceConfig PriceConfig { get; set; }
    }
}
