//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bus()
        {
            this.Schedules = new HashSet<Schedule>();
            this.VehicleSeats = new HashSet<VehicleSeat>();
        }
    
        public int BusID { get; set; }
        public string BusName { get; set; }
        public string RegistrationNumber { get; set; }
        public string ImageUrl { get; set; }
        public int Type { get; set; }
        public string Prefix { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> TotalSeats { get; set; }
        public Nullable<bool> IsEnable { get; set; }
        public Nullable<int> LocationId { get; set; }
    
        public virtual VehicleTypeLookup VehicleTypeLookup { get; set; }
        public virtual Location Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedule> Schedules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleSeat> VehicleSeats { get; set; }
    }
}
