//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientIntegration
    {
        public int Id { get; set; }
        public string Client_Name { get; set; }
        public string Refresh_Token { get; set; }
        public string Refresh_Token_Expiry { get; set; }
        public string Access_Token { get; set; }
        public string Access_Token_Expiry { get; set; }
        public Nullable<System.DateTime> Last_Journal_Entry { get; set; }
        public string Client_ID { get; set; }
        public string Client_Secret { get; set; }
    }
}
