//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractEmail
    {
        public int ContractID { get; set; }
        public int EmailMessageID { get; set; }
        public bool SendEmailOnAcceptance { get; set; }
        public bool IncludeContractAsPDF { get; set; }
        public bool IsEnable { get; set; }
    
        public virtual Contract Contract { get; set; }
        public virtual EmailMessage EmailMessage { get; set; }
    }
}
