//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractAssertion
    {
        public int ContractAssertionID { get; set; }
        public int ContractID { get; set; }
        public bool ShowCheckBox { get; set; }
        public bool AssertionRequired { get; set; }
        public string AssertionText { get; set; }
        public string AssertionHyperlinkText { get; set; }
        public string AssertionHyperlinkUrl { get; set; }
        public bool IsEnable { get; set; }
    
        public virtual Contract Contract { get; set; }
    }
}
