//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contract()
        {
            this.ContractAssertions = new HashSet<ContractAssertion>();
            this.StudentContracts = new HashSet<StudentContract>();
        }
    
        public int ContractID { get; set; }
        public int ContractTypeID { get; set; }
        public string ContractNumber { get; set; }
        public string ContractName { get; set; }
        public byte ContractVersion { get; set; }
        public string ContractReference { get; set; }
        public string ContractDescription { get; set; }
        public string ContractNotes { get; set; }
        public bool IsActive { get; set; }
        public bool IsEnable { get; set; }
        public bool IsPublish { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> LocationId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractAssertion> ContractAssertions { get; set; }
        public virtual ContractContent ContractContent { get; set; }
        public virtual ContractEmail ContractEmail { get; set; }
        public virtual ContractType ContractType { get; set; }
        public virtual ContractSignature ContractSignature { get; set; }
        public virtual Location Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentContract> StudentContracts { get; set; }
    }
}
