//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CorespondencePlaceHolder
    {
        public int id { get; set; }
        public string PlaceHolderKey { get; set; }
        public string Description { get; set; }
        public int ActionId { get; set; }
    }
}
