//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailScheduler
    {
        public int ID { get; set; }
        public string ScheduleName { get; set; }
        public string Type { get; set; }
        public string SubType { get; set; }
        public string TaskName { get; set; }
        public Nullable<bool> Recurrence { get; set; }
        public Nullable<System.DateTime> LastRun { get; set; }
        public Nullable<System.DateTime> NextRun { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> EmailSenderID { get; set; }
        public string EmailMessageBody { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<bool> IsEnable { get; set; }
        public string SendTo { get; set; }
        public Nullable<int> LocationId { get; set; }
        public bool IsSent { get; set; }
        public string EmailSubject { get; set; }
        public Nullable<System.DateTime> ExecutionTime { get; set; }
        public Nullable<System.DateTime> Fromdate { get; set; }
        public Nullable<System.DateTime> Todate { get; set; }
    
        public virtual EmailSender EmailSender { get; set; }
        public virtual Location Location { get; set; }
    }
}
