//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailSender
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmailSender()
        {
            this.EmailMessages = new HashSet<EmailMessage>();
            this.EmailSchedulers = new HashSet<EmailScheduler>();
        }
    
        public int EmailSenderID { get; set; }
        public string EmailSenderName { get; set; }
        public string EmailSenderDescription { get; set; }
        public bool IsActive { get; set; }
        public string FromAddress { get; set; }
        public string FromName { get; set; }
        public string EmailPassword { get; set; }
        public string CC { get; set; }
        public string BCC { get; set; }
        public string ReplyToAddress { get; set; }
        public string EmailSignature { get; set; }
        public bool IsEnable { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailMessage> EmailMessages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailScheduler> EmailSchedulers { get; set; }
    }
}
