//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailVerification
    {
        public int Id { get; set; }
        public string EmailAddress { get; set; }
        public string VerificationCode { get; set; }
        public bool Verified { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> VerifiedDate { get; set; }
    }
}
