//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailMessage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmailMessage()
        {
            this.ContractEmails = new HashSet<ContractEmail>();
        }
    
        public int EmailMessageID { get; set; }
        public int EmailSenderID { get; set; }
        public string EmailMessageName { get; set; }
        public string EmailMessageDescription { get; set; }
        public string EmailMessageSubject { get; set; }
        public bool IsActive { get; set; }
        public string EmailMessageBody { get; set; }
        public bool IsEnable { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> ActionId { get; set; }
        public Nullable<int> LocationId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractEmail> ContractEmails { get; set; }
        public virtual EmailSender EmailSender { get; set; }
        public virtual Location Location { get; set; }
    }
}
