//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int Id { get; set; }
        public int PersonID { get; set; }
        public int PlacementId { get; set; }
        public int QuestionId { get; set; }
        public int Rating { get; set; }
        public string Description { get; set; }
    
        public virtual BedSpacePlacement BedSpacePlacement { get; set; }
        public virtual Person Person { get; set; }
        public virtual Question Question { get; set; }
    }
}
