//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class GenerateInspection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GenerateInspection()
        {
            this.InspectionRatingDatas = new HashSet<InspectionRatingData>();
        }
    
        public int ID { get; set; }
        public int InspectionID { get; set; }
        public int BedSpaceID { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public int Student_Status { get; set; }
        public int Staff_Status { get; set; }
        public int Maintenance_Status { get; set; }
        public string Maintenance_Remarks { get; set; }
        public Nullable<bool> IsEnable { get; set; }
        public Nullable<int> InspectionActionID { get; set; }
        public string SecureKey { get; set; }
        public string StudentRemarks { get; set; }
        public Nullable<int> StaffResult { get; set; }
        public Nullable<int> StudentResult { get; set; }
        public Nullable<int> StudentId { get; set; }
    
        public virtual BedSpace BedSpace { get; set; }
        public virtual Inspection Inspection { get; set; }
        public virtual Status Status { get; set; }
        public virtual Status Status1 { get; set; }
        public virtual Status Status2 { get; set; }
        public virtual Status Status3 { get; set; }
        public virtual Status Status4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InspectionRatingData> InspectionRatingDatas { get; set; }
        public virtual Person Person { get; set; }
    }
}
