//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class InpectionFieldsSelected
    {
        public int InspectionFieldID { get; set; }
        public int InspectionID { get; set; }
        public int InspectionFieldValue { get; set; }
    
        public virtual Inspection Inspection { get; set; }
        public virtual Inspection Inspection1 { get; set; }
    }
}
