//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class InspectionRatingListItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InspectionRatingListItem()
        {
            this.InspectionRatingDatas = new HashSet<InspectionRatingData>();
        }
    
        public int InspectionRatingListItemID { get; set; }
        public int InspectionRatingListID { get; set; }
        public string InspectionRatingListItemName { get; set; }
        public string InspectionRatingListItemDescription { get; set; }
        public int InspectionRatingListItemPercentOfCharge { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InspectionRatingData> InspectionRatingDatas { get; set; }
        public virtual InspectionRatingList InspectionRatingList { get; set; }
    }
}
