//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class InspectionField
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InspectionField()
        {
            this.InspectionRatingDatas = new HashSet<InspectionRatingData>();
        }
    
        public int InspectionFieldsID { get; set; }
        public int InspectionRatingListID { get; set; }
        public string ModelName { get; set; }
        public string LongLabel { get; set; }
        public string ShortLabel { get; set; }
        public string OrgGroup { get; set; }
        public bool IsActive { get; set; }
        public bool IsEnable { get; set; }
        public bool AllowNotes { get; set; }
        public bool AllowImage { get; set; }
        public bool AllowExternalIdentifier { get; set; }
        public bool AssociatedWithMonetary { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual InspectionRatingList InspectionRatingList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InspectionRatingData> InspectionRatingDatas { get; set; }
    }
}
