//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inspection()
        {
            this.GenerateInspections = new HashSet<GenerateInspection>();
            this.InpectionFieldsSelecteds = new HashSet<InpectionFieldsSelected>();
            this.InpectionFieldsSelecteds1 = new HashSet<InpectionFieldsSelected>();
        }
    
        public int InspectionID { get; set; }
        public int InspectionType { get; set; }
        public Nullable<int> InspectionToCompareAgainst { get; set; }
        public string InspectionName { get; set; }
        public string InspectionDescription { get; set; }
        public int InspectionValidForDays { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> IsEnable { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GenerateInspection> GenerateInspections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InpectionFieldsSelected> InpectionFieldsSelecteds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InpectionFieldsSelected> InpectionFieldsSelecteds1 { get; set; }
        public virtual InspectionToCompareAgainst InspectionToCompareAgainst1 { get; set; }
        public virtual InspectionType InspectionType1 { get; set; }
    }
}
