//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class InspectionRatingData
    {
        public int ID { get; set; }
        public int AssignedFieldID { get; set; }
        public int ratingListID { get; set; }
        public int GeneratedInspectionID { get; set; }
        public int SelectetRatinglistitemID { get; set; }
        public string RatingNote { get; set; }
        public string RatingimageUrl { get; set; }
        public Nullable<bool> IsEnable { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual GenerateInspection GenerateInspection { get; set; }
        public virtual InspectionField InspectionField { get; set; }
        public virtual InspectionRatingList InspectionRatingList { get; set; }
        public virtual InspectionRatingListItem InspectionRatingListItem { get; set; }
    }
}
