//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntegrationWebhookDispatchLog
    {
        public int Id { get; set; }
        public int SubscriptionId { get; set; }
        public string EventType { get; set; }
        public string Payload { get; set; }
        public Nullable<int> ResponseCode { get; set; }
        public bool Success { get; set; }
        public System.DateTime AttemptedAt { get; set; }
        public string ErrorMessage { get; set; }
    }
}
