//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoicingRevenueDetail
    {
        public int Id { get; set; }
        public System.DateTime Month { get; set; }
        public int Days { get; set; }
        public int InvoicingDetailId { get; set; }
        public decimal Revenue { get; set; }
        public decimal DeferredRevenue { get; set; }
    
        public virtual InvoicingDetail InvoicingDetail { get; set; }
    }
}
