//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoicing
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoicing()
        {
            this.InvoiceTaxDetails = new HashSet<InvoiceTaxDetail>();
            this.Invoicing1 = new HashSet<Invoicing>();
            this.InvoicingDetails = new HashSet<InvoicingDetail>();
            this.StudentLedgers = new HashSet<StudentLedger>();
            this.StudentCreditNoteDetails = new HashSet<StudentCreditNoteDetail>();
        }
    
        public int Id { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public string Code { get; set; }
        public int StudentId { get; set; }
        public string Remarks { get; set; }
        public decimal TotalPrice { get; set; }
        public decimal TaxAmount { get; set; }
        public decimal NetAmount { get; set; }
        public string TaxIds { get; set; }
        public bool IsApproved { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public int LocationId { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<int> InvoiceTypeId { get; set; }
        public Nullable<int> TermID { get; set; }
        public Nullable<bool> Refunded { get; set; }
        public Nullable<int> ParentInvoiceId { get; set; }
        public string ZohoInvoiceId { get; set; }
        public Nullable<decimal> TotalDiscountAmount { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> BilledUpToDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceTaxDetail> InvoiceTaxDetails { get; set; }
        public virtual InvoiceTypeLookup InvoiceTypeLookup { get; set; }
        public virtual Location Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoicing> Invoicing1 { get; set; }
        public virtual Invoicing Invoicing2 { get; set; }
        public virtual Person Person { get; set; }
        public virtual UserMaster UserMaster { get; set; }
        public virtual UserMaster UserMaster1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoicingDetail> InvoicingDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentLedger> StudentLedgers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentCreditNoteDetail> StudentCreditNoteDetails { get; set; }
    }
}
