//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobConfiguration
    {
        public int Id { get; set; }
        public int CategoryId { get; set; }
        public string PropertyName { get; set; }
        public string PropertyValue { get; set; }
        public string FirstExecutionOn { get; set; }
        public Nullable<int> FirstExecutionActionId { get; set; }
        public string SecondExecutionOn { get; set; }
        public Nullable<int> SecondExecutionActionId { get; set; }
        public bool IsNotify { get; set; }
        public bool IsEmail { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual JobActionLookup JobActionLookup { get; set; }
        public virtual JobActionLookup JobActionLookup1 { get; set; }
    }
}
