//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationSetting
    {
        public int id { get; set; }
        public int LocationId { get; set; }
        public decimal RegistrationFee { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CodeOfConduct_EN { get; set; }
        public string CodeOfConduct_AR { get; set; }
        public string TermsAndCondition_EN { get; set; }
        public string TermsAndCondition_AR { get; set; }
        public string CompanyName { get; set; }
        public string VATNo { get; set; }
        public string PaymentGateWay { get; set; }
        public string ReferralProgram { get; set; }
        public bool ReferralIsActive { get; set; }
        public string Bank { get; set; }
        public string Branch { get; set; }
        public string Title { get; set; }
        public string Account { get; set; }
        public string Currency { get; set; }
        public string SwiftCode { get; set; }
        public string IBAN { get; set; }
        public Nullable<bool> PreCheckinDocumentationIsActive { get; set; }
        public Nullable<int> Def_Acc_Rec { get; set; }
        public Nullable<int> Def_Acc_Pay { get; set; }
        public Nullable<int> Def_Acc_Discount { get; set; }
        public Nullable<int> Def_Acc_Adv_Pay { get; set; }
        public string TransactionPassword { get; set; }
    
        public virtual ChartOfAccount ChartOfAccount { get; set; }
        public virtual ChartOfAccount ChartOfAccount1 { get; set; }
        public virtual ChartOfAccount ChartOfAccount2 { get; set; }
        public virtual ChartOfAccount ChartOfAccount11 { get; set; }
    }
}
