//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Movie()
        {
            this.MovieShows = new HashSet<MovieShow>();
            this.MovieVoteCampaignDetails = new HashSet<MovieVoteCampaignDetail>();
        }
    
        public int MovieID { get; set; }
        public string MovieTitle { get; set; }
        public string MovieDetails { get; set; }
        public string BannerImageUrl { get; set; }
        public string MonthImageUrl { get; set; }
        public string VoteImageUrl { get; set; }
        public bool IsEnable { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovieShow> MovieShows { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovieVoteCampaignDetail> MovieVoteCampaignDetails { get; set; }
    }
}
