//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieVoteCampaignDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MovieVoteCampaignDetail()
        {
            this.MovieVotes = new HashSet<MovieVote>();
        }
    
        public int MovieVoteCampaignDetailID { get; set; }
        public int MovieVoteCampaignID { get; set; }
        public int MovieID { get; set; }
        public bool IsEnable { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Movie Movie { get; set; }
        public virtual MovieVoteCampaign MovieVoteCampaign { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovieVote> MovieVotes { get; set; }
    }
}
