//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieVote
    {
        public int MovieVoteID { get; set; }
        public int MovieVoteCampaignDetailID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string UserEmail { get; set; }
        public bool LikeMovie { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual MovieVoteCampaignDetail MovieVoteCampaignDetail { get; set; }
    }
}
