//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieVoteCampaign
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MovieVoteCampaign()
        {
            this.MovieVoteCampaignDetails = new HashSet<MovieVoteCampaignDetail>();
        }
    
        public int MovieVoteCampaignID { get; set; }
        public string Description { get; set; }
        public System.DateTime ShowDate { get; set; }
        public string ShowTime { get; set; }
        public string HallNo { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsEnable { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovieVoteCampaignDetail> MovieVoteCampaignDetails { get; set; }
    }
}
