//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieShow
    {
        public int MovieShowID { get; set; }
        public int MovieID { get; set; }
        public System.DateTime ShowDate { get; set; }
        public string ShowTime { get; set; }
        public string HallNo { get; set; }
        public string ShowDetails { get; set; }
        public bool IsEnable { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Movie Movie { get; set; }
    }
}
