//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsDetail
    {
        public int NewsDetailID { get; set; }
        public int NewsID { get; set; }
        public string ContentType { get; set; }
        public string ContentValue { get; set; }
        public string Ar_ContentValue { get; set; }
    
        public virtual News News { get; set; }
    }
}
