//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public News()
        {
            this.NewsDetails = new HashSet<NewsDetail>();
        }
    
        public int NewsID { get; set; }
        public int NewsCategoryID { get; set; }
        public string Heading { get; set; }
        public string Ar_Heading { get; set; }
        public string Headline { get; set; }
        public string Ar_Headline { get; set; }
        public System.DateTime NewsDate { get; set; }
        public string Thumbnail { get; set; }
        public string Ar_Thumbnail { get; set; }
        public string HeadlineImage { get; set; }
        public string Ar_HeadlineImage { get; set; }
        public string SourceLink { get; set; }
        public bool IsActive { get; set; }
        public bool IsEnable { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual NewsCategory NewsCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NewsDetail> NewsDetails { get; set; }
    }
}
