//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentGateway
    {
        public int Id { get; set; }
        public string TranRef { get; set; }
        public string PaymentInvoiceId { get; set; }
        public string CustomerRef { get; set; }
        public string Currency { get; set; }
        public string CardLastDigits { get; set; }
        public string Message { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string InvoiceId { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
