//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payment()
        {
            this.BillingAddresses = new HashSet<BillingAddress>();
            this.BookingMarts = new HashSet<BookingMart>();
        }
    
        public int PaymentID { get; set; }
        public int PaymentMethodID { get; set; }
        public Nullable<int> BookingID { get; set; }
        public decimal Amount { get; set; }
        public string Currency { get; set; }
        public string CardLastDigits { get; set; }
        public string TranRef { get; set; }
        public string Message { get; set; }
        public bool IsEnable { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillingAddress> BillingAddresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingMart> BookingMarts { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
    }
}
