//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaymentType()
        {
            this.StudentCreditNotes = new HashSet<StudentCreditNote>();
        }
    
        public int PaymentId { get; set; }
        public string PayementName { get; set; }
        public bool IsActive { get; set; }
        public bool IsEnable { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdateBy { get; set; }
        public string Code { get; set; }
        public string KeyCode { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<int> LocationId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentCreditNote> StudentCreditNotes { get; set; }
        public virtual ChartOfAccount ChartOfAccount { get; set; }
        public virtual Location Location { get; set; }
    }
}
