//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PMSEntities : DbContext
    {
        public PMSEntities()
            : base("name=PMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountType> AccountTypes { get; set; }
        public virtual DbSet<AllRoomFeature> AllRoomFeatures { get; set; }
        public virtual DbSet<AuditLogDetail> AuditLogDetails { get; set; }
        public virtual DbSet<AuditLog> AuditLogs { get; set; }
        public virtual DbSet<BedSpace> BedSpaces { get; set; }
        public virtual DbSet<BedSpacePlacement> BedSpacePlacements { get; set; }
        public virtual DbSet<BedSpacePlacementMigration> BedSpacePlacementMigrations { get; set; }
        public virtual DbSet<BedSpaceStatusLookUp> BedSpaceStatusLookUps { get; set; }
        public virtual DbSet<BillingAddress> BillingAddresses { get; set; }
        public virtual DbSet<Booking> Bookings { get; set; }
        public virtual DbSet<BookingMart> BookingMarts { get; set; }
        public virtual DbSet<Bus> Buses { get; set; }
        public virtual DbSet<ChartOfAccount> ChartOfAccounts { get; set; }
        public virtual DbSet<ClientIntegration> ClientIntegrations { get; set; }
        public virtual DbSet<ContractAssertion> ContractAssertions { get; set; }
        public virtual DbSet<ContractContent> ContractContents { get; set; }
        public virtual DbSet<ContractEmail> ContractEmails { get; set; }
        public virtual DbSet<Contract> Contracts { get; set; }
        public virtual DbSet<ContractSignature> ContractSignatures { get; set; }
        public virtual DbSet<ContractType> ContractTypes { get; set; }
        public virtual DbSet<CorespondencePlaceHolder> CorespondencePlaceHolders { get; set; }
        public virtual DbSet<CorrespondenceAction> CorrespondenceActions { get; set; }
        public virtual DbSet<CreditNoteTypeLookup> CreditNoteTypeLookups { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<EmailMessage> EmailMessages { get; set; }
        public virtual DbSet<EmailScheduler> EmailSchedulers { get; set; }
        public virtual DbSet<EmailSender> EmailSenders { get; set; }
        public virtual DbSet<EmailSetting> EmailSettings { get; set; }
        public virtual DbSet<EmailVerification> EmailVerifications { get; set; }
        public virtual DbSet<EmergencyContact> EmergencyContacts { get; set; }
        public virtual DbSet<Feedback> Feedbacks { get; set; }
        public virtual DbSet<Floor> Floors { get; set; }
        public virtual DbSet<GenerateInspection> GenerateInspections { get; set; }
        public virtual DbSet<GroupLookup> GroupLookups { get; set; }
        public virtual DbSet<GroupRoleLookup> GroupRoleLookups { get; set; }
        public virtual DbSet<InpectionFieldsSelected> InpectionFieldsSelecteds { get; set; }
        public virtual DbSet<InspectionField> InspectionFields { get; set; }
        public virtual DbSet<InspectionRatingData> InspectionRatingDatas { get; set; }
        public virtual DbSet<InspectionRatingList> InspectionRatingLists { get; set; }
        public virtual DbSet<InspectionRatingListItem> InspectionRatingListItems { get; set; }
        public virtual DbSet<Inspection> Inspections { get; set; }
        public virtual DbSet<InspectionToCompareAgainst> InspectionToCompareAgainsts { get; set; }
        public virtual DbSet<InspectionType> InspectionTypes { get; set; }
        public virtual DbSet<InvoiceTaxDetail> InvoiceTaxDetails { get; set; }
        public virtual DbSet<InvoiceTypeLookup> InvoiceTypeLookups { get; set; }
        public virtual DbSet<Invoicing> Invoicings { get; set; }
        public virtual DbSet<InvoicingDetail> InvoicingDetails { get; set; }
        public virtual DbSet<InvoicingRevenueDetail> InvoicingRevenueDetails { get; set; }
        public virtual DbSet<JobActionLookup> JobActionLookups { get; set; }
        public virtual DbSet<JobConfiguration> JobConfigurations { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<LocationSetting> LocationSettings { get; set; }
        public virtual DbSet<MainMenu> MainMenus { get; set; }
        public virtual DbSet<Movie> Movies { get; set; }
        public virtual DbSet<MovieShow> MovieShows { get; set; }
        public virtual DbSet<MovieVoteCampaign> MovieVoteCampaigns { get; set; }
        public virtual DbSet<MovieVoteCampaignDetail> MovieVoteCampaignDetails { get; set; }
        public virtual DbSet<MovieVote> MovieVotes { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<NewsCategory> NewsCategories { get; set; }
        public virtual DbSet<NewsDetail> NewsDetails { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<PaymentGateway> PaymentGateways { get; set; }
        public virtual DbSet<PaymentMethod> PaymentMethods { get; set; }
        public virtual DbSet<PaymentType> PaymentTypes { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<PersonDocument> PersonDocuments { get; set; }
        public virtual DbSet<PersonGuest> PersonGuests { get; set; }
        public virtual DbSet<PreCheckInDocumentation> PreCheckInDocumentations { get; set; }
        public virtual DbSet<PriceConfig> PriceConfigs { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<RefundRequest> RefundRequests { get; set; }
        public virtual DbSet<RegisterSync> RegisterSyncs { get; set; }
        public virtual DbSet<RoleRight> RoleRights { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<RoomType> RoomTypes { get; set; }
        public virtual DbSet<RoomTypeDetail> RoomTypeDetails { get; set; }
        public virtual DbSet<RoomTypeFeature> RoomTypeFeatures { get; set; }
        public virtual DbSet<Route> Routes { get; set; }
        public virtual DbSet<RouteStope> RouteStopes { get; set; }
        public virtual DbSet<Schedule> Schedules { get; set; }
        public virtual DbSet<SeatsLookUp> SeatsLookUps { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<ServiceTypeLookup> ServiceTypeLookups { get; set; }
        public virtual DbSet<SpecialRequest> SpecialRequests { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Stop> Stops { get; set; }
        public virtual DbSet<StudentContract> StudentContracts { get; set; }
        public virtual DbSet<StudentCreditNote> StudentCreditNotes { get; set; }
        public virtual DbSet<StudentCreditNoteDetail> StudentCreditNoteDetails { get; set; }
        public virtual DbSet<StudentLedger> StudentLedgers { get; set; }
        public virtual DbSet<SubMenu> SubMenus { get; set; }
        public virtual DbSet<SubscriptionStatusLookup> SubscriptionStatusLookups { get; set; }
        public virtual DbSet<Sync> Syncs { get; set; }
        public virtual DbSet<SystemConfiguration> SystemConfigurations { get; set; }
        public virtual DbSet<Tax> Taxes { get; set; }
        public virtual DbSet<Temp> Temps { get; set; }
        public virtual DbSet<Term> Terms { get; set; }
        public virtual DbSet<Ticket> Tickets { get; set; }
        public virtual DbSet<TicketDetail> TicketDetails { get; set; }
        public virtual DbSet<TicketDetailAttachement> TicketDetailAttachements { get; set; }
        public virtual DbSet<TicketHistory> TicketHistories { get; set; }
        public virtual DbSet<TicketingGroupUser> TicketingGroupUsers { get; set; }
        public virtual DbSet<TicketPeriorityLookup> TicketPeriorityLookups { get; set; }
        public virtual DbSet<TicketStatusLookup> TicketStatusLookups { get; set; }
        public virtual DbSet<TimeSlotLookUp> TimeSlotLookUps { get; set; }
        public virtual DbSet<University> Universities { get; set; }
        public virtual DbSet<UserMaster> UserMasters { get; set; }
        public virtual DbSet<UserPreference> UserPreferences { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<VehicleBooking> VehicleBookings { get; set; }
        public virtual DbSet<VehiclePrice> VehiclePrices { get; set; }
        public virtual DbSet<VehiclePriceLookUp> VehiclePriceLookUps { get; set; }
        public virtual DbSet<VehicleSeat> VehicleSeats { get; set; }
        public virtual DbSet<VehicleSubscription> VehicleSubscriptions { get; set; }
        public virtual DbSet<VehicleTypeLookup> VehicleTypeLookups { get; set; }
        public virtual DbSet<PreferenceDetail> PreferenceDetails { get; set; }
        public virtual DbSet<StudentContracts_20221121> StudentContracts_20221121 { get; set; }
        public virtual DbSet<V_GetPersonsforDeposit> V_GetPersonsforDeposit { get; set; }
        public virtual DbSet<v_RommTypeDetail> v_RommTypeDetail { get; set; }
        public virtual DbSet<V_RoomTypePriceDetail> V_RoomTypePriceDetail { get; set; }
        public virtual DbSet<Voucher> Vouchers { get; set; }
        public virtual DbSet<VoucherDetail> VoucherDetails { get; set; }
        public virtual DbSet<V_PlacementList> V_PlacementList { get; set; }
        public virtual DbSet<V_GetInvoiceList> V_GetInvoiceList { get; set; }
        public virtual DbSet<V_GetPersonsforMiscellaneous> V_GetPersonsforMiscellaneous { get; set; }
        public virtual DbSet<Building> Buildings { get; set; }
        public virtual DbSet<PushNotificationLog> PushNotificationLogs { get; set; }
        public virtual DbSet<V_GetPaymentList> V_GetPaymentList { get; set; }
        public virtual DbSet<StudentDeviceToken> StudentDeviceTokens { get; set; }
        public virtual DbSet<IntegrationWebhookDispatchLog> IntegrationWebhookDispatchLogs { get; set; }
        public virtual DbSet<IntegrationWebhookSubscription> IntegrationWebhookSubscriptions { get; set; }
    
        public virtual int SPGetServicesDetailReport(string fromDate, string toDate, string serviceId, string studentId, string termId, string userId, string type)
        {
            var fromDateParameter = fromDate != null ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(string));
    
            var toDateParameter = toDate != null ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(string));
    
            var serviceIdParameter = serviceId != null ?
                new ObjectParameter("ServiceId", serviceId) :
                new ObjectParameter("ServiceId", typeof(string));
    
            var studentIdParameter = studentId != null ?
                new ObjectParameter("StudentId", studentId) :
                new ObjectParameter("StudentId", typeof(string));
    
            var termIdParameter = termId != null ?
                new ObjectParameter("TermId", termId) :
                new ObjectParameter("TermId", typeof(string));
    
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPGetServicesDetailReport", fromDateParameter, toDateParameter, serviceIdParameter, studentIdParameter, termIdParameter, userIdParameter, typeParameter);
        }
    
        public virtual ObjectResult<SPGetPaymentsDetailReport_Result> SPGetPaymentsDetailReport(string fromDate, string toDate, string paymentId, string studentId, string userId, string type)
        {
            var fromDateParameter = fromDate != null ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(string));
    
            var toDateParameter = toDate != null ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(string));
    
            var paymentIdParameter = paymentId != null ?
                new ObjectParameter("PaymentId", paymentId) :
                new ObjectParameter("PaymentId", typeof(string));
    
            var studentIdParameter = studentId != null ?
                new ObjectParameter("StudentId", studentId) :
                new ObjectParameter("StudentId", typeof(string));
    
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPGetPaymentsDetailReport_Result>("SPGetPaymentsDetailReport", fromDateParameter, toDateParameter, paymentIdParameter, studentIdParameter, userIdParameter, typeParameter);
        }
    
        public virtual int SPGetRevenueReport(string month, string isDefferd, string termId)
        {
            var monthParameter = month != null ?
                new ObjectParameter("Month", month) :
                new ObjectParameter("Month", typeof(string));
    
            var isDefferdParameter = isDefferd != null ?
                new ObjectParameter("IsDefferd", isDefferd) :
                new ObjectParameter("IsDefferd", typeof(string));
    
            var termIdParameter = termId != null ?
                new ObjectParameter("TermId", termId) :
                new ObjectParameter("TermId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPGetRevenueReport", monthParameter, isDefferdParameter, termIdParameter);
        }
    
        public virtual ObjectResult<GetInvoicePrintReport_Result> GetInvoicePrintReport(Nullable<int> invoiceId)
        {
            var invoiceIdParameter = invoiceId.HasValue ?
                new ObjectParameter("InvoiceId", invoiceId) :
                new ObjectParameter("InvoiceId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetInvoicePrintReport_Result>("GetInvoicePrintReport", invoiceIdParameter);
        }
    
        public virtual ObjectResult<GetPaymentTransactionPrintReport_Result> GetPaymentTransactionPrintReport(Nullable<int> studentLedgerId)
        {
            var studentLedgerIdParameter = studentLedgerId.HasValue ?
                new ObjectParameter("StudentLedgerId", studentLedgerId) :
                new ObjectParameter("StudentLedgerId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPaymentTransactionPrintReport_Result>("GetPaymentTransactionPrintReport", studentLedgerIdParameter);
        }
    
        public virtual ObjectResult<SPGetComplaintHistoryReport_Result> SPGetComplaintHistoryReport(Nullable<int> statusId, Nullable<int> createdBy, Nullable<int> updatedBy)
        {
            var statusIdParameter = statusId.HasValue ?
                new ObjectParameter("StatusId", statusId) :
                new ObjectParameter("StatusId", typeof(int));
    
            var createdByParameter = createdBy.HasValue ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(int));
    
            var updatedByParameter = updatedBy.HasValue ?
                new ObjectParameter("UpdatedBy", updatedBy) :
                new ObjectParameter("UpdatedBy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPGetComplaintHistoryReport_Result>("SPGetComplaintHistoryReport", statusIdParameter, createdByParameter, updatedByParameter);
        }
    
        public virtual int SPNotificationReport(string type, string id)
        {
            var typeParameter = type != null ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(string));
    
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPNotificationReport", typeParameter, idParameter);
        }
    
        public virtual int SPGetRoomInventoryReport(Nullable<int> start, Nullable<int> length)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(int));
    
            var lengthParameter = length.HasValue ?
                new ObjectParameter("length", length) :
                new ObjectParameter("length", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPGetRoomInventoryReport", startParameter, lengthParameter);
        }
    
        public virtual ObjectResult<string> SPGetBookingReport(string fromDate, string toDate)
        {
            var fromDateParameter = fromDate != null ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(string));
    
            var toDateParameter = toDate != null ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SPGetBookingReport", fromDateParameter, toDateParameter);
        }
    
        public virtual int SPGetBookingExpired()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPGetBookingExpired");
        }
    
        public virtual int GetDashboardStat(Nullable<int> locationId)
        {
            var locationIdParameter = locationId.HasValue ?
                new ObjectParameter("LocationId", locationId) :
                new ObjectParameter("LocationId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetDashboardStat", locationIdParameter);
        }
    
        public virtual ObjectResult<GetPendingFeeAssesmentThisMonth_Result> GetPendingFeeAssesmentThisMonth(Nullable<int> locationId)
        {
            var locationIdParameter = locationId.HasValue ?
                new ObjectParameter("LocationId", locationId) :
                new ObjectParameter("LocationId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPendingFeeAssesmentThisMonth_Result>("GetPendingFeeAssesmentThisMonth", locationIdParameter);
        }
    
        public virtual ObjectResult<GetAvailableRoomsForLandingPage_Result> GetAvailableRoomsForLandingPage(Nullable<int> locationId, string university)
        {
            var locationIdParameter = locationId.HasValue ?
                new ObjectParameter("LocationId", locationId) :
                new ObjectParameter("LocationId", typeof(int));
    
            var universityParameter = university != null ?
                new ObjectParameter("University", university) :
                new ObjectParameter("University", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAvailableRoomsForLandingPage_Result>("GetAvailableRoomsForLandingPage", locationIdParameter, universityParameter);
        }
    
        public virtual ObjectResult<GetInvoicesTillNextWeek_Result> GetInvoicesTillNextWeek(Nullable<int> locationId)
        {
            var locationIdParameter = locationId.HasValue ?
                new ObjectParameter("LocationId", locationId) :
                new ObjectParameter("LocationId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetInvoicesTillNextWeek_Result>("GetInvoicesTillNextWeek", locationIdParameter);
        }
    }
}
