//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreCheckInDocumentation
    {
        public int id { get; set; }
        public int PersonId { get; set; }
        public int PlacementId { get; set; }
        public int BookingId { get; set; }
        public string DocumentationName { get; set; }
        public string PersonCode { get; set; }
        public string PersonFullName { get; set; }
        public string DocumentationContent { get; set; }
        public string StudentSignature { get; set; }
        public bool IsSigned { get; set; }
        public string SignedBy { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string DocumentationUrl { get; set; }
        public string DocumentationKey { get; set; }
    
        public virtual BedSpacePlacement BedSpacePlacement { get; set; }
        public virtual Person Person { get; set; }
        public virtual UserMaster UserMaster { get; set; }
    }
}
