//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreferenceDetail
    {
        public int ID { get; set; }
        public int PrefID { get; set; }
        public bool Preference { get; set; }
        public int PersonID { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual UserPreference UserPreference { get; set; }
    }
}
