//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceConfig
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PriceConfig()
        {
            this.Bookings = new HashSet<Booking>();
        }
    
        public int PriceConfigID { get; set; }
        public int TermID { get; set; }
        public int RoomTypeID { get; set; }
        public decimal Price { get; set; }
        public decimal InitialDeposit { get; set; }
        public string Currency { get; set; }
        public bool IsEnable { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> LocationId { get; set; }
        public bool IsAvailable { get; set; }
        public int OrderBy { get; set; }
        public Nullable<decimal> CleaningCharge { get; set; }
        public bool IsWebsiteAvailable { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual Location Location { get; set; }
        public virtual RoomType RoomType { get; set; }
        public virtual Term Term { get; set; }
    }
}
