//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PushNotificationLog
    {
        public long ID { get; set; }
        public string Title { get; set; }
        public string MessageBody { get; set; }
        public string Topic { get; set; }
        public int SentByUserID { get; set; }
        public string SentByUserName { get; set; }
        public string SentByEmail { get; set; }
        public System.DateTime SentOn { get; set; }
        public Nullable<int> DeliveredDeviceCount { get; set; }
        public bool IsEnable { get; set; }
    
        public virtual UserMaster UserMaster { get; set; }
    }
}
