//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefundRequest
    {
        public int ID { get; set; }
        public int PersonID { get; set; }
        public string MyriadID { get; set; }
        public string Email { get; set; }
        public string BankAccount { get; set; }
        public string AccountNumber { get; set; }
        public string IFSCCode { get; set; }
        public string Signature { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
