//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoomType()
        {
            this.PriceConfigs = new HashSet<PriceConfig>();
            this.Rooms = new HashSet<Room>();
            this.RoomTypeFeatures = new HashSet<RoomTypeFeature>();
        }
    
        public int RoomTypeID { get; set; }
        public string RoomCode { get; set; }
        public string RoomName { get; set; }
        public string RoomDescription { get; set; }
        public string RoomArea { get; set; }
        public bool IsEnable { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public bool IsClubRoom { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string Ar_RoomName { get; set; }
        public string Ar_RoomDescription { get; set; }
        public string BedSpace { get; set; }
        public Nullable<decimal> Actual_Price { get; set; }
        public string Ar_Thumbnail { get; set; }
        public string Thumbnail { get; set; }
        public string RoomInstruction { get; set; }
        public string Ar_RoomInstruction { get; set; }
    
        public virtual Location Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PriceConfig> PriceConfigs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Room> Rooms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomTypeFeature> RoomTypeFeatures { get; set; }
    }
}
