//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomTypeDetail
    {
        public int ID { get; set; }
        public int RoomTypeID { get; set; }
        public string Description { get; set; }
        public string Ar_Description { get; set; }
        public string ThumbnailUrl { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<bool> IsRoomFeature { get; set; }
        public Nullable<bool> Web { get; set; }
        public Nullable<bool> Android { get; set; }
        public Nullable<bool> iOS { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<bool> IsEnable { get; set; }
    }
}
