//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomTypeFeature
    {
        public int RoomTypeFeatureId { get; set; }
        public int RoomTypeID { get; set; }
        public int AllRomFeatureID { get; set; }
        public bool IsEnable { get; set; }
        public Nullable<int> OrderBy { get; set; }
    
        public virtual AllRoomFeature AllRoomFeature { get; set; }
        public virtual RoomType RoomType { get; set; }
    }
}
