//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RouteStope
    {
        public int RouteStopID { get; set; }
        public int RouteID { get; set; }
        public int StopID { get; set; }
        public int StopNumber { get; set; }
        public Nullable<System.DateTime> StopTime { get; set; }
        public int TotalStopTime { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Route Route { get; set; }
        public virtual Stop Stop { get; set; }
    }
}
