//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Route()
        {
            this.RouteStopes = new HashSet<RouteStope>();
            this.Schedules = new HashSet<Schedule>();
            this.VehiclePrices = new HashSet<VehiclePrice>();
        }
    
        public int RouteID { get; set; }
        public string RouteName { get; set; }
        public Nullable<System.DateTime> DepartureTime { get; set; }
        public Nullable<bool> IsEnable { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public int TotalTravelTime { get; set; }
        public Nullable<int> LocationId { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual Route Routes1 { get; set; }
        public virtual Route Route1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RouteStope> RouteStopes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedule> Schedules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehiclePrice> VehiclePrices { get; set; }
    }
}
