//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Schedule()
        {
            this.VehicleBookings = new HashSet<VehicleBooking>();
        }
    
        public int ScheduleID { get; set; }
        public string ScheduleName { get; set; }
        public Nullable<bool> IsEnable { get; set; }
        public System.DateTime FromDate { get; set; }
        public int RouteId { get; set; }
        public int VehicleId { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public int DepartureTimeId { get; set; }
        public Nullable<int> LocationId { get; set; }
    
        public virtual Bus Bus { get; set; }
        public virtual Location Location { get; set; }
        public virtual Route Route { get; set; }
        public virtual TimeSlotLookUp TimeSlotLookUp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleBooking> VehicleBookings { get; set; }
    }
}
