//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Service()
        {
            this.InvoicingDetails = new HashSet<InvoicingDetail>();
        }
    
        public int ServiceId { get; set; }
        public string ServiceName { get; set; }
        public decimal ServiceAmount { get; set; }
        public bool IsActive { get; set; }
        public bool IsEnable { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> AccountId { get; set; }
        public bool IsPrePlacementService { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> TaxId { get; set; }
        public Nullable<int> LocationId { get; set; }
    
        public virtual ChartOfAccount ChartOfAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoicingDetail> InvoicingDetails { get; set; }
        public virtual Location Location { get; set; }
        public virtual ServiceTypeLookup ServiceTypeLookup { get; set; }
    }
}
