//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecialRequest
    {
        public int ID { get; set; }
        public string PreferableFloor { get; set; }
        public string PreferableView { get; set; }
        public string Religions { get; set; }
        public string Nationalities { get; set; }
        public string Universities { get; set; }
        public string Agerange { get; set; }
        public Nullable<int> PersonID { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
