//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stop()
        {
            this.RouteStopes = new HashSet<RouteStope>();
        }
    
        public int StopID { get; set; }
        public string StopName { get; set; }
        public string Lat { get; set; }
        public string Long { get; set; }
        public Nullable<System.DateTime> StopTime { get; set; }
        public string DistanceFromDeparture { get; set; }
        public string StopFullName { get; set; }
        public int ScheduleID { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> LocationId { get; set; }
    
        public virtual Location Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RouteStope> RouteStopes { get; set; }
    }
}
