//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentCreditNoteDetail
    {
        public int Id { get; set; }
        public int StudentCreditNoteId { get; set; }
        public int InvoiceId { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
    
        public virtual Invoicing Invoicing { get; set; }
        public virtual StudentCreditNote StudentCreditNote { get; set; }
        public virtual UserMaster UserMaster { get; set; }
    }
}
