//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentLedger
    {
        public int Id { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public string Code { get; set; }
        public Nullable<int> InvoiceId { get; set; }
        public int StudentId { get; set; }
        public Nullable<decimal> DebitAmount { get; set; }
        public Nullable<decimal> CreditAmount { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> PaymentTypeId { get; set; }
        public string PaymentTypeName { get; set; }
        public bool IsApproved { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<int> CreditNoteId { get; set; }
        public string PaymentReferenceNumber { get; set; }
        public Nullable<int> LookupId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public bool IsReversedPayment { get; set; }
    
        public virtual Invoicing Invoicing { get; set; }
        public virtual Location Location { get; set; }
        public virtual Person Person { get; set; }
        public virtual StudentCreditNote StudentCreditNote { get; set; }
        public virtual UserMaster UserMaster { get; set; }
        public virtual UserMaster UserMaster1 { get; set; }
    }
}
