//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentContracts_20221121
    {
        public int id { get; set; }
        public int PersonId { get; set; }
        public int PlacementId { get; set; }
        public int BookingId { get; set; }
        public int ContractId { get; set; }
        public string ContractName { get; set; }
        public string PersonCode { get; set; }
        public string PersonFullName { get; set; }
        public decimal GrossAmount { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public decimal NetAmount { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<decimal> RegistrationFee { get; set; }
        public decimal SecurityDeposit { get; set; }
        public string ContractContent { get; set; }
        public string StudentSignature { get; set; }
        public bool IsSigned { get; set; }
        public string SignedBy { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int updatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string ContractUrl { get; set; }
        public string ContractKey { get; set; }
    }
}
