//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentCreditNote
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentCreditNote()
        {
            this.StudentCreditNoteDetails = new HashSet<StudentCreditNoteDetail>();
            this.StudentLedgers = new HashSet<StudentLedger>();
        }
    
        public int ID { get; set; }
        public string Code { get; set; }
        public int StudentId { get; set; }
        public string Reason { get; set; }
        public int Type { get; set; }
        public int LocationId { get; set; }
        public Nullable<int> Percentage { get; set; }
        public decimal Amount { get; set; }
        public int Status { get; set; }
        public bool IsEnable { get; set; }
        public bool IsUtilized { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<decimal> AdjustedAmount { get; set; }
        public Nullable<int> BookingId { get; set; }
        public Nullable<int> PaymentTypeId { get; set; }
    
        public virtual CreditNoteTypeLookup CreditNoteTypeLookup { get; set; }
        public virtual Location Location { get; set; }
        public virtual PaymentType PaymentType { get; set; }
        public virtual Person Person { get; set; }
        public virtual Status Status1 { get; set; }
        public virtual UserMaster UserMaster { get; set; }
        public virtual UserMaster UserMaster1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentCreditNoteDetail> StudentCreditNoteDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentLedger> StudentLedgers { get; set; }
    }
}
