//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentDeviceToken
    {
        public long ID { get; set; }
        public int UserId { get; set; }
        public Nullable<int> PersonId { get; set; }
        public string DeviceToken { get; set; }
        public string Platform { get; set; }
        public string DeviceId { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime LastLoginAt { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public bool IsEnable { get; set; }
    
        public virtual UserMaster UserMaster { get; set; }
    }
}
