//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubMenu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubMenu()
        {
            this.RoleRights = new HashSet<RoleRight>();
        }
    
        public int SubMenuId { get; set; }
        public int MainMenuId { get; set; }
        public string ControllerName { get; set; }
        public string ActionName { get; set; }
        public string RoleName { get; set; }
        public string DisplayName { get; set; }
        public string SubMenuDescription { get; set; }
        public byte OrderNumber { get; set; }
        public bool ShouldDisplay { get; set; }
        public bool IsEnable { get; set; }
    
        public virtual MainMenu MainMenu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoleRight> RoleRights { get; set; }
    }
}
