//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sync
    {
        public int Id { get; set; }
        public int SyncId { get; set; }
        public string PropertyValue { get; set; }
        public string Scope { get; set; }
        public Nullable<System.DateTime> FirstExecutionOn { get; set; }
        public Nullable<System.DateTime> LastUsedOn { get; set; }
        public Nullable<System.DateTime> NextExecutionOn { get; set; }
        public Nullable<System.DateTime> RevokeOn { get; set; }
        public string RevokeBy { get; set; }
        public Nullable<int> FirstJobActionId { get; set; }
        public Nullable<int> NextJobActionId { get; set; }
        public bool Status { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsExecuted { get; set; }
    
        public virtual RegisterSync RegisterSync { get; set; }
    }
}
