//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tax
    {
        public int TaxId { get; set; }
        public string TaxName { get; set; }
        public decimal TaxPercentage { get; set; }
        public bool IsEnable { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public string Code { get; set; }
        public Nullable<int> AccountId { get; set; }
        public string ZohoTaxId { get; set; }
        public string QuickBooksTaxId { get; set; }
        public Nullable<int> LocationId { get; set; }
    
        public virtual ChartOfAccount ChartOfAccount { get; set; }
        public virtual Location Location { get; set; }
        public virtual Tax Taxes1 { get; set; }
        public virtual Tax Tax1 { get; set; }
    }
}
