//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Term
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Term()
        {
            this.PriceConfigs = new HashSet<PriceConfig>();
        }
    
        public int TermID { get; set; }
        public string TermName { get; set; }
        public Nullable<System.DateTime> TermStartDate { get; set; }
        public Nullable<System.DateTime> TermEndDate { get; set; }
        public string TermDescription { get; set; }
        public bool IsEnable { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string Ar_TermDescription { get; set; }
        public string AR_TermName { get; set; }
        public Nullable<int> Min_Duration { get; set; }
        public string Room_Occupancy { get; set; }
        public string Ar_Room_Occupancy { get; set; }
        public string Room_Standared { get; set; }
        public string Ar_Room_Standared { get; set; }
        public string DurationType { get; set; }
        public Nullable<bool> IsPublished { get; set; }
        public Nullable<int> FrequencyId { get; set; }
        public Nullable<int> UniversityId { get; set; }
    
        public virtual Location Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PriceConfig> PriceConfigs { get; set; }
        public virtual University University { get; set; }
        public virtual VehiclePriceLookUp VehiclePriceLookUp { get; set; }
    }
}
