//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ticket()
        {
            this.TicketDetails = new HashSet<TicketDetail>();
            this.TicketHistories = new HashSet<TicketHistory>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int LocationId { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> PriorityId { get; set; }
        public string Source { get; set; }
        public int StatusId { get; set; }
        public bool IsEnable { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<int> AssignTo { get; set; }
        public Nullable<int> IssueBy { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> ResolvedDate { get; set; }
        public string Code { get; set; }
        public Nullable<int> IssueByStaff { get; set; }
        public Nullable<int> GroupId { get; set; }
        public string IssueByEmail { get; set; }
        public string FullName { get; set; }
        public string Phone { get; set; }
    
        public virtual GroupLookup GroupLookup { get; set; }
        public virtual Location Location { get; set; }
        public virtual Person Person { get; set; }
        public virtual TicketPeriorityLookup TicketPeriorityLookup { get; set; }
        public virtual TicketStatusLookup TicketStatusLookup { get; set; }
        public virtual UserMaster UserMaster { get; set; }
        public virtual UserMaster UserMaster1 { get; set; }
        public virtual UserMaster UserMaster2 { get; set; }
        public virtual UserMaster UserMaster3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketDetail> TicketDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketHistory> TicketHistories { get; set; }
    }
}
