//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_GetPaymentList
    {
        public int Id { get; set; }
        public int StudentId { get; set; }
        public string TransactionCode { get; set; }
        public string Location { get; set; }
        public string MyriadID { get; set; }
        public string FullName { get; set; }
        public string InvoiceCode { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<int> InvoiceId { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> CreditAmount { get; set; }
        public Nullable<decimal> DebitAmount { get; set; }
        public string TransactionType { get; set; }
        public string PaymentName { get; set; }
        public string PaymentReferenceNumber { get; set; }
        public bool IsApproved { get; set; }
        public string CreatedBy { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<int> CreditNoteId { get; set; }
        public Nullable<int> VoucherId { get; set; }
        public string VoucherCode { get; set; }
        public Nullable<int> LocationId { get; set; }
        public bool IsReversedPayment { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string Currency { get; set; }
    }
}
