//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_GetInvoiceList
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Location { get; set; }
        public int LocationId { get; set; }
        public string MyriadID { get; set; }
        public string FullName { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Remarks { get; set; }
        public int StudentId { get; set; }
        public decimal NetAmount { get; set; }
        public bool Status { get; set; }
        public Nullable<bool> isPaid { get; set; }
        public Nullable<bool> Refunded { get; set; }
        public Nullable<int> InvoiceTypeId { get; set; }
        public Nullable<int> ParentInvoiceId { get; set; }
        public Nullable<int> VoucherId { get; set; }
        public string VoucherCode { get; set; }
        public string CreatedBy { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<decimal> TotalDiscountAmount { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string ServiceName { get; set; }
        public decimal PendingBalance { get; set; }
        public decimal TotalBalanceOfResident { get; set; }
    }
}
