//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PlacementList
    {
        public int BedSpacePlacementID { get; set; }
        public int BookingID { get; set; }
        public int PersonID { get; set; }
        public string ReferralCode { get; set; }
        public System.DateTime MoveIn { get; set; }
        public System.DateTime MoveOut { get; set; }
        public Nullable<System.DateTime> CheckIn { get; set; }
        public Nullable<System.DateTime> CheckOut { get; set; }
        public string Title { get; set; }
        public string FullName { get; set; }
        public string MyriadID { get; set; }
        public string Code { get; set; }
        public string University { get; set; }
        public string Gender { get; set; }
        public string Phone { get; set; }
        public System.DateTime DOB { get; set; }
        public string Email { get; set; }
        public decimal Price { get; set; }
        public int TermID { get; set; }
        public int PriceConfigID { get; set; }
        public string Block { get; set; }
        public string BedSpace { get; set; }
        public string Room { get; set; }
        public string RoomType { get; set; }
        public string Requests { get; set; }
        public string Commitment { get; set; }
        public bool BedSpacePlacementIsEnable { get; set; }
        public System.DateTime BedSpacePlacementCreatedDate { get; set; }
        public Nullable<int> LocationID { get; set; }
        public string LocationName { get; set; }
        public Nullable<int> GuestCount { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> BilledUpto { get; set; }
    }
}
