//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_RommTypeDetail
    {
        public int OrderBy { get; set; }
        public string Prefix { get; set; }
        public string Ar_RoomDescription { get; set; }
        public string Ar_RoomName { get; set; }
        public string RoomName { get; set; }
        public string RoomDescription { get; set; }
        public string Thumbnail { get; set; }
        public string Ar_Thumbnail { get; set; }
        public string RoomArea { get; set; }
        public string RoomCode { get; set; }
        public int RoomTypeID { get; set; }
        public string BedSpace { get; set; }
        public int PriceConfigID { get; set; }
        public decimal Price { get; set; }
        public decimal InitialDeposit { get; set; }
        public string Currency { get; set; }
        public Nullable<int> LocationId { get; set; }
        public int TermID { get; set; }
        public string TermName { get; set; }
        public string TermDescription { get; set; }
        public string Ar_TermDescription { get; set; }
        public string AR_TermName { get; set; }
        public bool IsClubRoom { get; set; }
        public Nullable<System.DateTime> TermStartDate { get; set; }
        public Nullable<System.DateTime> TermEndDate { get; set; }
        public Nullable<int> Min_Duration { get; set; }
        public string Room_Occupancy { get; set; }
        public string Ar_Room_Occupancy { get; set; }
        public string Room_Standared { get; set; }
        public string Ar_Room_Standared { get; set; }
        public bool IsAvailable { get; set; }
        public string RoomInstruction { get; set; }
        public string Ar_RoomInstruction { get; set; }
        public Nullable<decimal> Actual_Price { get; set; }
        public string Bank { get; set; }
        public string Branch { get; set; }
        public string Title { get; set; }
        public string Account { get; set; }
        public string LocationSettingsCurrency { get; set; }
        public string SwiftCode { get; set; }
        public string Email { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<int> FrequencyId { get; set; }
    }
}
