//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_RoomTypePriceDetail
    {
        public Nullable<int> LocationId { get; set; }
        public int RoomTypePriceId { get; set; }
        public int RoomTypeID { get; set; }
        public int TermID { get; set; }
        public decimal Price { get; set; }
        public string Name { get; set; }
        public string ArabicRoomName { get; set; }
        public string RoomCode { get; set; }
        public string RoomDescription { get; set; }
        public string ArabicRoomDescription { get; set; }
        public decimal TotalCommitmentPrice { get; set; }
        public string DurationDescription { get; set; }
        public string ArabicDurationDescription { get; set; }
        public decimal InitialDeposit { get; set; }
        public string DurationType { get; set; }
        public Nullable<System.DateTime> TermStartDate { get; set; }
        public Nullable<System.DateTime> TermEndDate { get; set; }
        public string TermName { get; set; }
        public int OrderBy { get; set; }
        public string Currency { get; set; }
        public string Bank { get; set; }
        public string Branch { get; set; }
        public string Title { get; set; }
        public string Account { get; set; }
        public string SwiftCode { get; set; }
    }
}
