//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleSubscription
    {
        public int SubscriptionID { get; set; }
        public int StudentId { get; set; }
        public int VehiclePriceId { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public bool IsEnable { get; set; }
        public int FrequencyId { get; set; }
        public decimal SubscriptionPrice { get; set; }
        public int SubscriptionStatus { get; set; }
        public Nullable<int> LocationId { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual Person Person { get; set; }
        public virtual SubscriptionStatusLookup SubscriptionStatusLookup { get; set; }
        public virtual VehiclePrice VehiclePrice { get; set; }
        public virtual VehiclePriceLookUp VehiclePriceLookUp { get; set; }
    }
}
