//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleBooking
    {
        public int Id { get; set; }
        public int ScheduleID { get; set; }
        public int StudentId { get; set; }
        public int SeatId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Status { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Schedule Schedule { get; set; }
        public virtual VehicleSeat VehicleSeat { get; set; }
    }
}
